AWSTemplateFormatVersion: "2010-09-09"
Description: Lambda used to implement the various task need in the process of increasing the price of subscriptions

Parameters:
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
      - PROD
      - CODE
      - DEV
    Default: CODE

Mappings:
  StageMap:
    DEV:
      SecretsVersion: "6559354e-556f-4609-a89f-222824495d5d"
      EarliestStartDate: 2020-05-15
      BucketName: price-migration-engine-dev
      SQSQueueName: contributions-thanks-dev
    CODE:
      SecretsVersion: "52529e0a-438b-4b63-8a08-35f158ed0bee"
      EarliestStartDate: 2020-05-15
      BucketName: price-migration-engine-code
      SQSQueueName: contributions-thanks-dev
    PROD:
      SecretsVersion: "dd295c21-39df-47d0-b3b2-0d420ee3b055"
      EarliestStartDate: 2020-08-02
      BucketName: price-migration-engine-prod
      SQSQueueName: contributions-thanks

Resources:

  CohortTableAccessPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CohortTableAccessPolicy
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:Query
              - dynamodb:UpdateItem
              - dynamodb:PutItem
            Resource:
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/PriceMigrationEngine${Stage}"
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/PriceMigrationEngine${Stage}/*"
      Roles:
        - Ref: PriceMigrationEngineEstimationLambdaRole
        - Ref: PriceMigrationEngineSalesforcePriceCreationLambdaRole
        - Ref: PriceMigrationEngineAmendmentLambdaRole
        - Ref: PriceMigrationEngineSubscriptionIdUploadLambdaRole
        - Ref: PriceMigrationEngineNotificationLambdaRole
        - Ref: PriceMigrationEngineSalesforceNotificationDateUpdateLambdaRole

  PriceMigrationEngineEstimationLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: LambdaPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - lambda:InvokeFunction
                Resource:
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/price-migration-engine-estimation-lambda-${Stage}:log-stream:*"

  PriceMigrationEngineSalesforcePriceCreationLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: LambdaPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - lambda:InvokeFunction
                Resource:
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/price-migration-engine-salesforce-price-rise-lambda-${Stage}:log-stream:*"

  PriceMigrationEngineAmendmentLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: LambdaPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - lambda:InvokeFunction
                Resource:
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/price-migration-engine-amendment-lambda-${Stage}:log-stream:*"

  PriceMigrationEngineSubscriptionIdUploadLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: LambdaPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - lambda:InvokeFunction
                Resource:
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/price-migration-engine-subscription-id-upload-lambda-${Stage}:log-stream:*"
        - PolicyName: S3BucketPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  - !Sub
                    - "arn:aws:s3:::${BucketName}/*"
                    - {BucketName: !FindInMap [StageMap, !Ref Stage, BucketName]}
    DependsOn:
      - S3Bucket

  PriceMigrationEngineNotificationLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: LambdaPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - lambda:InvokeFunction
                Resource:
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/price-migration-engine-notification-email-lambda-${Stage}:log-stream:*"
        - PolicyName: SendNotificationRequestSQSMessage
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - sqs:GetQueueUrl
                  - sqs:SendMessage
                Resource: !Sub
                  - "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${QueueName}"
                  - { QueueName: !FindInMap [ StageMap, !Ref Stage, SQSQueueName ] }

  PriceMigrationEngineSalesforceNotificationDateUpdateLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: LambdaPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - lambda:InvokeFunction
                Resource:
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/price-migration-engine-salesforce-notification-date-update-lambda-${Stage}:log-stream:*"

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !FindInMap [StageMap, !Ref Stage, BucketName]

  PriceMigrationEngineEstimationLambda:
    Type: AWS::Lambda::Function
    Properties:
      Description: Lambda used to create estimated price, start date and other details of a price rise
      FunctionName:
        !Sub price-migration-engine-estimation-lambda-${Stage}
      Code:
        S3Bucket: membership-dist
        S3Key: !Sub membership/${Stage}/price-migration-engine-lambda/price-migration-engine-lambda.jar
      Handler: pricemigrationengine.handlers.EstimationHandler::handleRequest
      Environment:
        Variables:
          stage: !Ref Stage
          zuoraApiHost:
            !Sub
              - '{{resolve:secretsmanager:price-migration-engine-lambda-${Stage}:SecretString:zuoraApiHost::${SecretsVersion}}}'
              - SecretsVersion: !FindInMap [StageMap, !Ref Stage, SecretsVersion]
          zuoraClientId:
            !Sub
              - '{{resolve:secretsmanager:price-migration-engine-lambda-${Stage}:SecretString:zuoraClientId::${SecretsVersion}}}'
              - SecretsVersion: !FindInMap [StageMap, !Ref Stage, SecretsVersion]
          zuoraClientSecret:
            !Sub
              - '{{resolve:secretsmanager:price-migration-engine-lambda-${Stage}:SecretString:zuoraClientSecret::${SecretsVersion}}}'
              - SecretsVersion: !FindInMap [StageMap, !Ref Stage, SecretsVersion]
          earliestStartDate: !FindInMap [StageMap, !Ref Stage, EarliestStartDate]
          batchSize: 100
      Role:
        Fn::GetAtt:
          - PriceMigrationEngineEstimationLambdaRole
          - Arn
      MemorySize: 1536
      Runtime: java8
      Timeout: 900
    DependsOn:
      - PriceMigrationEngineEstimationLambdaRole

  PriceMigrationEngineSalesforcePriceCreationLambda:
    Type: AWS::Lambda::Function
    Properties:
      Description: Lambda used to create Price_Rise__c objects in salesforce realting to the price rise.
      FunctionName:
        !Sub price-migration-engine-salesforce-price-rise-lambda-${Stage}
      Code:
        S3Bucket: membership-dist
        S3Key: !Sub membership/${Stage}/price-migration-engine-lambda/price-migration-engine-lambda.jar
      Handler: pricemigrationengine.handlers.SalesforcePriceRiseCreationHandler::handleRequest
      Environment:
        Variables:
          stage: !Ref Stage
          batchSize: 100
          salesforceAuthUrl:
            !Sub
            - '{{resolve:secretsmanager:price-migration-engine-lambda-${Stage}:SecretString:salesforceAuthUrl::${SecretsVersion}}}'
            - SecretsVersion: !FindInMap [StageMap, !Ref Stage, SecretsVersion]
          salesforceClientId:
            !Sub
            - '{{resolve:secretsmanager:price-migration-engine-lambda-${Stage}:SecretString:salesforceClientId::${SecretsVersion}}}'
            - SecretsVersion: !FindInMap [StageMap, !Ref Stage, SecretsVersion]
          salesforceClientSecret:
            !Sub
            - '{{resolve:secretsmanager:price-migration-engine-lambda-${Stage}:SecretString:salesforceClientSecret::${SecretsVersion}}}'
            - SecretsVersion: !FindInMap [StageMap, !Ref Stage, SecretsVersion]
          salesforceUserName:
            !Sub
            - '{{resolve:secretsmanager:price-migration-engine-lambda-${Stage}:SecretString:salesforceUserName::${SecretsVersion}}}'
            - SecretsVersion: !FindInMap [StageMap, !Ref Stage, SecretsVersion]
          salesforcePassword:
            !Sub
            - '{{resolve:secretsmanager:price-migration-engine-lambda-${Stage}:SecretString:salesforcePassword::${SecretsVersion}}}'
            - SecretsVersion: !FindInMap [StageMap, !Ref Stage, SecretsVersion]
          salesforceToken:
            !Sub
            - '{{resolve:secretsmanager:price-migration-engine-lambda-${Stage}:SecretString:salesforceToken::${SecretsVersion}}}'
            - SecretsVersion: !FindInMap [StageMap, !Ref Stage, SecretsVersion]
      Role:
        Fn::GetAtt:
          - PriceMigrationEngineSalesforcePriceCreationLambdaRole
          - Arn
      MemorySize: 1536
      Runtime: java8
      Timeout: 900
    DependsOn:
      - PriceMigrationEngineSalesforcePriceCreationLambdaRole

  PriceMigrationEngineAmendmentLambda:
    Type: AWS::Lambda::Function
    Properties:
      Description: Adds price-rise amendments to subscriptions.
      FunctionName:
        !Sub price-migration-engine-amendment-lambda-${Stage}
      Code:
        S3Bucket: membership-dist
        S3Key: !Sub membership/${Stage}/price-migration-engine-lambda/price-migration-engine-lambda.jar
      Handler: pricemigrationengine.handlers.AmendmentHandler::handleRequest
      Environment:
        Variables:
          stage: !Ref Stage
          zuoraApiHost:
            !Sub
            - '{{resolve:secretsmanager:price-migration-engine-lambda-${Stage}:SecretString:zuoraApiHost::${SecretsVersion}}}'
            - SecretsVersion: !FindInMap [StageMap, !Ref Stage, SecretsVersion]
          zuoraClientId:
            !Sub
            - '{{resolve:secretsmanager:price-migration-engine-lambda-${Stage}:SecretString:zuoraClientId::${SecretsVersion}}}'
            - SecretsVersion: !FindInMap [StageMap, !Ref Stage, SecretsVersion]
          zuoraClientSecret:
            !Sub
            - '{{resolve:secretsmanager:price-migration-engine-lambda-${Stage}:SecretString:zuoraClientSecret::${SecretsVersion}}}'
            - SecretsVersion: !FindInMap [StageMap, !Ref Stage, SecretsVersion]
          earliestStartDate: !FindInMap [StageMap, !Ref Stage, EarliestStartDate]
          batchSize: 100
      Role:
        Fn::GetAtt:
          - PriceMigrationEngineAmendmentLambdaRole
          - Arn
      MemorySize: 1536
      Runtime: java8
      Timeout: 900
    DependsOn:
      - PriceMigrationEngineAmendmentLambdaRole

  PriceMigrationEngineSubscriptionIdUploadLambda:
    Type: AWS::Lambda::Function
    Properties:
      Description: Uploads subscription id CSV files into price migration engine.
      FunctionName:
        !Sub price-migration-engine-subscription-id-upload-lambda-${Stage}
      Code:
        S3Bucket: membership-dist
        S3Key: !Sub membership/${Stage}/price-migration-engine-lambda/price-migration-engine-lambda.jar
      Handler: pricemigrationengine.handlers.SubscriptionIdUploadHandler::handleRequest
      Environment:
        Variables:
          stage: !Ref Stage
          batchSize: 100
      Role:
        Fn::GetAtt:
          - PriceMigrationEngineSubscriptionIdUploadLambdaRole
          - Arn
      MemorySize: 1536
      Runtime: java8
      Timeout: 900
    DependsOn:
      - PriceMigrationEngineSubscriptionIdUploadLambdaRole
      - S3Bucket

  PriceMigrationEngineNotificationLambda:
    Type: AWS::Lambda::Function
    Properties:
      Description: Sends notification mails to users telling them about the price rise
      FunctionName:
        !Sub price-migration-engine-notification-lambda-${Stage}
      Code:
        S3Bucket: membership-dist
        S3Key: !Sub membership/${Stage}/price-migration-engine-lambda/price-migration-engine-lambda.jar
      Handler: pricemigrationengine.handlers.NotificationHandler::handleRequest
      Environment:
        Variables:
          stage: !Ref Stage
          batchSize: 100
          salesforceAuthUrl:
            !Sub
            - '{{resolve:secretsmanager:price-migration-engine-lambda-${Stage}:SecretString:salesforceAuthUrl::${SecretsVersion}}}'
            - SecretsVersion: !FindInMap [StageMap, !Ref Stage, SecretsVersion]
          salesforceClientId:
            !Sub
            - '{{resolve:secretsmanager:price-migration-engine-lambda-${Stage}:SecretString:salesforceClientId::${SecretsVersion}}}'
            - SecretsVersion: !FindInMap [StageMap, !Ref Stage, SecretsVersion]
          salesforceClientSecret:
            !Sub
            - '{{resolve:secretsmanager:price-migration-engine-lambda-${Stage}:SecretString:salesforceClientSecret::${SecretsVersion}}}'
            - SecretsVersion: !FindInMap [StageMap, !Ref Stage, SecretsVersion]
          salesforceUserName:
            !Sub
            - '{{resolve:secretsmanager:price-migration-engine-lambda-${Stage}:SecretString:salesforceUserName::${SecretsVersion}}}'
            - SecretsVersion: !FindInMap [StageMap, !Ref Stage, SecretsVersion]
          salesforcePassword:
            !Sub
            - '{{resolve:secretsmanager:price-migration-engine-lambda-${Stage}:SecretString:salesforcePassword::${SecretsVersion}}}'
            - SecretsVersion: !FindInMap [StageMap, !Ref Stage, SecretsVersion]
          salesforceToken:
            !Sub
            - '{{resolve:secretsmanager:price-migration-engine-lambda-${Stage}:SecretString:salesforceToken::${SecretsVersion}}}'
            - SecretsVersion: !FindInMap [StageMap, !Ref Stage, SecretsVersion]
          sqsEmailQueueName:
            !Sub
            - '{{resolve:secretsmanager:price-migration-engine-lambda-${Stage}:SecretString:sqsEmailQueueName::${SecretsVersion}}}'
            - SecretsVersion: !FindInMap [StageMap, !Ref Stage, SecretsVersion]
      Role:
        Fn::GetAtt:
          - PriceMigrationEngineNotificationLambdaRole
          - Arn
      MemorySize: 1536
      Runtime: java8
      Timeout: 900
    DependsOn:
      - PriceMigrationEngineNotificationLambdaRole

  PriceMigrationEngineSalesforceNotificationDateUpdateLambda:
    Type: AWS::Lambda::Function
    Properties:
      Description: Lambda used to update Price_Rise__c objects in salesforce with the notification sent date.
      FunctionName:
        !Sub price-migration-engine-salesforce-notification-date-lambda-${Stage}
      Code:
        S3Bucket: membership-dist
        S3Key: !Sub membership/${Stage}/price-migration-engine-lambda/price-migration-engine-lambda.jar
      Handler: pricemigrationengine.handlers.SalesforceNotificationDateUpdateHandler::handleRequest
      Environment:
        Variables:
          stage: !Ref Stage
          batchSize: 100
          salesforceAuthUrl:
            !Sub
            - '{{resolve:secretsmanager:price-migration-engine-lambda-${Stage}:SecretString:salesforceAuthUrl::${SecretsVersion}}}'
            - SecretsVersion: !FindInMap [StageMap, !Ref Stage, SecretsVersion]
          salesforceClientId:
            !Sub
            - '{{resolve:secretsmanager:price-migration-engine-lambda-${Stage}:SecretString:salesforceClientId::${SecretsVersion}}}'
            - SecretsVersion: !FindInMap [StageMap, !Ref Stage, SecretsVersion]
          salesforceClientSecret:
            !Sub
            - '{{resolve:secretsmanager:price-migration-engine-lambda-${Stage}:SecretString:salesforceClientSecret::${SecretsVersion}}}'
            - SecretsVersion: !FindInMap [StageMap, !Ref Stage, SecretsVersion]
          salesforceUserName:
            !Sub
            - '{{resolve:secretsmanager:price-migration-engine-lambda-${Stage}:SecretString:salesforceUserName::${SecretsVersion}}}'
            - SecretsVersion: !FindInMap [StageMap, !Ref Stage, SecretsVersion]
          salesforcePassword:
            !Sub
            - '{{resolve:secretsmanager:price-migration-engine-lambda-${Stage}:SecretString:salesforcePassword::${SecretsVersion}}}'
            - SecretsVersion: !FindInMap [StageMap, !Ref Stage, SecretsVersion]
          salesforceToken:
            !Sub
            - '{{resolve:secretsmanager:price-migration-engine-lambda-${Stage}:SecretString:salesforceToken::${SecretsVersion}}}'
            - SecretsVersion: !FindInMap [StageMap, !Ref Stage, SecretsVersion]
      Role:
        Fn::GetAtt:
          - PriceMigrationEngineSalesforceNotificationDateUpdateLambdaRole
          - Arn
      MemorySize: 1536
      Runtime: java8
      Timeout: 900
    DependsOn:
      - PriceMigrationEngineSalesforceNotificationDateUpdateLambdaRole

Outputs:
  PriceMigrationEngineEstimationLambdaOutput:
    Value: !GetAtt PriceMigrationEngineEstimationLambda.Arn
    Export:
      Name: !Sub "${AWS::StackName}-EstimatingLambda"
  PriceMigrationEngineSalesforcePriceCreationLambdaOutput:
    Value: !GetAtt PriceMigrationEngineSalesforcePriceCreationLambda.Arn
    Export:
      Name: !Sub "${AWS::StackName}-CreatingSalesforceRecordsLambda"
