AWSTemplateFormatVersion: "2010-09-09"
Description: Lambda used to implement the various task need in the process of increasing the price of subscriptions

Parameters:
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
      - PROD
      - CODE
      - DEV
    Default: CODE

Mappings:
  StageMap:
    DEV:
      SecretsVersion: "a98f33b0-1db0-4462-bc53-5faabb42b097"
    CODE:
      SecretsVersion: "3137cb2d-629e-48d2-aefa-b966301f7667"
    PROD:
      SecretsVersion: "4351dd97-033d-464e-bea6-f9112c5a2a23"


Resources:
  PriceMigrationEngineLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: LambdaPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - lambda:InvokeFunction
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/price-migration-engine-lambda-${Stage}:log-stream:*"
        - PolicyName: DynamoDBAccessPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:Query
                  - dynamodb:UpdateItem
                Resource:
                  - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/PriceMigrationEngine${Stage}"
                  - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/PriceMigrationEngine${Stage}/*"

  PriceMigrationEngineLambda:
    Type: AWS::Lambda::Function
    Properties:
      Description: Lambda used to implement the various task need in the process of increasing the price of subscriptions
      FunctionName:
        !Sub price-migration-engine-lambda-${Stage}
      Code:
        S3Bucket: membership-dist
        S3Key: !Sub membership/${Stage}/price-migration-engine-lambda/price-migration-engine-lambda.jar
      Handler: pricemigrationengine.handlers.EstimationHandler::handleRequest
      Environment:
        Variables:
          stage: !Ref Stage
          zuoraApiHost:
            !Sub
              - '{{resolve:secretsmanager:price-migration-engine-lambda-${Stage}:SecretString:zuoraApiHost::${SecretsVersion}}}'
              - SecretsVersion: !FindInMap [StageMap, !Ref Stage, SecretsVersion]
          zuoraClientId:
            !Sub
              - '{{resolve:secretsmanager:price-migration-engine-lambda-${Stage}:SecretString:zuoraClientId::${SecretsVersion}}}'
              - SecretsVersion: !FindInMap [StageMap, !Ref Stage, SecretsVersion]
          zuoraClientSecret:
            !Sub
              - '{{resolve:secretsmanager:price-migration-engine-lambda-${Stage}:SecretString:zuoraClientSecret::${SecretsVersion}}}'
              - SecretsVersion: !FindInMap [StageMap, !Ref Stage, SecretsVersion]
          earliestStartDate: 2020-05-15
          batchSize: 100
      Role:
        Fn::GetAtt:
          - PriceMigrationEngineLambdaRole
          - Arn
      MemorySize: 1536
      Runtime: java8
      Timeout: 300
    DependsOn:
      - PriceMigrationEngineLambdaRole
