AWSTemplateFormatVersion: "2010-09-09"
Description: Lambda used to implement the various task need in the process of increasing the price of subscriptions

Parameters:
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
      - PROD
      - CODE
      - DEV
    Default: CODE

Mappings:
  StageMap:
    DEV:
      SecretsVersion: "e159cf84-2ae6-4600-8444-d8c4c74531d5"
      EarliestStartDate: 2020-05-15
    CODE:
      SecretsVersion: "a0df5201-f2d9-4699-a704-805e7c1df2ee"
      EarliestStartDate: 2020-05-15
    PROD:
      SecretsVersion: "0ef81375-18ec-4a94-b4b9-eb4c399e3455"
      EarliestStartDate: 2020-12-25


Resources:
  PriceMigrationEngineLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: LambdaPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - lambda:InvokeFunction
                Resource:
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/price-migration-engine-estimation-lambda-${Stage}:log-stream:*"
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/price-migration-engine-salesforce-price-rise-lambda-${Stage}:log-stream:*"
                  - !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/price-migration-engine-amendment-lambda-${Stage}:log-stream:*"
        - PolicyName: DynamoDBAccessPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:Query
                  - dynamodb:UpdateItem
                Resource:
                  - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/PriceMigrationEngine${Stage}"
                  - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/PriceMigrationEngine${Stage}/*"

  PriceMigrationEngineEstimationLambda:
    Type: AWS::Lambda::Function
    Properties:
      Description: Lambda used to create estimated price, start date and other details of a price rise
      FunctionName:
        !Sub price-migration-engine-estimation-lambda-${Stage}
      Code:
        S3Bucket: membership-dist
        S3Key: !Sub membership/${Stage}/price-migration-engine-lambda/price-migration-engine-lambda.jar
      Handler: pricemigrationengine.handlers.EstimationHandler::handleRequest
      Environment:
        Variables:
          stage: !Ref Stage
          zuoraApiHost:
            !Sub
              - '{{resolve:secretsmanager:price-migration-engine-lambda-${Stage}:SecretString:zuoraApiHost::${SecretsVersion}}}'
              - SecretsVersion: !FindInMap [StageMap, !Ref Stage, SecretsVersion]
          zuoraClientId:
            !Sub
              - '{{resolve:secretsmanager:price-migration-engine-lambda-${Stage}:SecretString:zuoraClientId::${SecretsVersion}}}'
              - SecretsVersion: !FindInMap [StageMap, !Ref Stage, SecretsVersion]
          zuoraClientSecret:
            !Sub
              - '{{resolve:secretsmanager:price-migration-engine-lambda-${Stage}:SecretString:zuoraClientSecret::${SecretsVersion}}}'
              - SecretsVersion: !FindInMap [StageMap, !Ref Stage, SecretsVersion]
          earliestStartDate: !FindInMap [StageMap, !Ref Stage, EarliestStartDate]
          batchSize: 100
      Role:
        Fn::GetAtt:
          - PriceMigrationEngineLambdaRole
          - Arn
      MemorySize: 1536
      Runtime: java8
      Timeout: 300
    DependsOn:
      - PriceMigrationEngineLambdaRole

  PriceMigrationEngineSalesforcePriceCreationLambda:
    Type: AWS::Lambda::Function
    Properties:
      Description: Lambda used to create Price_Rise__c objects in salesforce realting to the price rise.
      FunctionName:
        !Sub price-migration-engine-salesforce-price-rise-lambda-${Stage}
      Code:
        S3Bucket: membership-dist
        S3Key: !Sub membership/${Stage}/price-migration-engine-lambda/price-migration-engine-lambda.jar
      Handler: pricemigrationengine.handlers.SalesforcePriceRiseCreationHandler::handleRequest
      Environment:
        Variables:
          stage: !Ref Stage
          batchSize: 100
          salesforceAuthUrl:
            !Sub
            - '{{resolve:secretsmanager:price-migration-engine-lambda-${Stage}:SecretString:salesforceAuthUrl::${SecretsVersion}}}'
            - SecretsVersion: !FindInMap [StageMap, !Ref Stage, SecretsVersion]
          salesforceClientId:
            !Sub
            - '{{resolve:secretsmanager:price-migration-engine-lambda-${Stage}:SecretString:salesforceClientId::${SecretsVersion}}}'
            - SecretsVersion: !FindInMap [StageMap, !Ref Stage, SecretsVersion]
          salesforceClientSecret:
            !Sub
            - '{{resolve:secretsmanager:price-migration-engine-lambda-${Stage}:SecretString:salesforceClientSecret::${SecretsVersion}}}'
            - SecretsVersion: !FindInMap [StageMap, !Ref Stage, SecretsVersion]
          salesforceUserName:
            !Sub
            - '{{resolve:secretsmanager:price-migration-engine-lambda-${Stage}:SecretString:salesforceUserName::${SecretsVersion}}}'
            - SecretsVersion: !FindInMap [StageMap, !Ref Stage, SecretsVersion]
          salesforcePassword:
            !Sub
            - '{{resolve:secretsmanager:price-migration-engine-lambda-${Stage}:SecretString:salesforcePassword::${SecretsVersion}}}'
            - SecretsVersion: !FindInMap [StageMap, !Ref Stage, SecretsVersion]
          salesforceToken:
            !Sub
            - '{{resolve:secretsmanager:price-migration-engine-lambda-${Stage}:SecretString:salesforceToken::${SecretsVersion}}}'
            - SecretsVersion: !FindInMap [StageMap, !Ref Stage, SecretsVersion]
      Role:
        Fn::GetAtt:
          - PriceMigrationEngineLambdaRole
          - Arn
      MemorySize: 1536
      Runtime: java8
      Timeout: 300
    DependsOn:
      - PriceMigrationEngineLambdaRole

  PriceMigrationEngineAmendmentLambda:
    Type: AWS::Lambda::Function
    Properties:
      Description: Adds price-rise amendments to subscriptions.
      FunctionName:
        !Sub price-migration-engine-amendment-lambda-${Stage}
      Code:
        S3Bucket: membership-dist
        S3Key: !Sub membership/${Stage}/price-migration-engine-lambda/price-migration-engine-lambda.jar
      Handler: pricemigrationengine.handlers.AmendmentHandler::handleRequest
      Environment:
        Variables:
          stage: !Ref Stage
          zuoraApiHost:
            !Sub
            - '{{resolve:secretsmanager:price-migration-engine-lambda-${Stage}:SecretString:zuoraApiHost::${SecretsVersion}}}'
            - SecretsVersion: !FindInMap [StageMap, !Ref Stage, SecretsVersion]
          zuoraClientId:
            !Sub
            - '{{resolve:secretsmanager:price-migration-engine-lambda-${Stage}:SecretString:zuoraClientId::${SecretsVersion}}}'
            - SecretsVersion: !FindInMap [StageMap, !Ref Stage, SecretsVersion]
          zuoraClientSecret:
            !Sub
            - '{{resolve:secretsmanager:price-migration-engine-lambda-${Stage}:SecretString:zuoraClientSecret::${SecretsVersion}}}'
            - SecretsVersion: !FindInMap [StageMap, !Ref Stage, SecretsVersion]
          earliestStartDate: !FindInMap [StageMap, !Ref Stage, EarliestStartDate]
          batchSize: 100
      Role:
        Fn::GetAtt:
          - PriceMigrationEngineLambdaRole
          - Arn
      MemorySize: 1536
      Runtime: java8
      Timeout: 300
    DependsOn:
      - PriceMigrationEngineLambdaRole
