AWSTemplateFormatVersion: "2010-09-09"

Description: Generate the DynamoDB tables for the price-migration-engine

Parameters:
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
      - DEV
      - CODE
      - PROD
    Default: CODE

Resources:
  PriceMigrationEngineDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub PriceMigrationEngine${Stage}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "SubscriptionNumber"
          AttributeType: "S"
        - AttributeName: "ProcessingStage"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "SubscriptionNumber"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        - IndexName: "ProcessingStageIndex"
          KeySchema:
            - AttributeName: "ProcessingStage"
              KeyType: "HASH"
          Projection:
            ProjectionType: "KEYS_ONLY"