AWSTemplateFormatVersion: "2010-09-09"

Description: Generate the DynamoDB tables for the price-migration-engine

Parameters:
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
      - DEV
      - CODE
      - PROD
    Default: CODE

Resources:
  AtomWorkshopPreviewDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub price-migration-engine-${Stage}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "subscription-number"
          AttributeType: "S"
        - AttributeName: "is-sf-showing-estimate"
          AttributeType: "n"
        - AttributeName: "is-braze-warned"
          AttributeType: "n"
        - AttributeName: "is-amended"
          AttributeType: "n"
        - AttributeName: "is-sf-showing-amendment"
          AttributeType: "n"
        - AttributeName: "is-braze-confirmed"
          AttributeType: "n"
        - AttributeName: "is-cancelled"
          AttributeType: "n"
      KeySchema:
        - AttributeName: "subscription-number"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        - IndexName: "is-sf-showing-estimate-index"
          KeySchema:
            - AttributeName: "is-sf-showing-estimate"
              KeyType: "HASH"
          Projection:
            ProjectionType: "KEYS_ONLY"
        - IndexName: "is-braze-warned-index"
          KeySchema:
            - AttributeName: "is-braze-warned"
              KeyType: "HASH"
          Projection:
            ProjectionType: "KEYS_ONLY"
        - IndexName: "is-amended-index"
          KeySchema:
            - AttributeName: "is-amended"
              KeyType: "HASH"
          Projection:
            ProjectionType: "KEYS_ONLY"
        - IndexName: "is-sf-showing-amendment-index"
          KeySchema:
            - AttributeName: "is-sf-showing-amendment"
              KeyType: "HASH"
          Projection:
            ProjectionType: "KEYS_ONLY"
        - IndexName: "is-braze-confirmed-index"
          KeySchema:
            - AttributeName: "is-braze-confirmed"
              KeyType: "HASH"
          Projection:
            ProjectionType: "KEYS_ONLY"
