AWSTemplateFormatVersion: "2010-09-09"

Description: Generate the DynamoDB tables for the price-migration-engine

Parameters:
  Stage:
    Description: Stage name
    Type: String
    AllowedValues:
      - DEV
      - CODE
      - PROD
    Default: CODE

Resources:
  PriceMigrationEngineDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub PriceMigrationEngine${Stage}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "subscriptionNumber"
          AttributeType: "S"
        - AttributeName: "processingStage"
          AttributeType: "S"
        - AttributeName: "startDate"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "subscriptionNumber"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        - IndexName: "ProcessingStageIndexV2"
          KeySchema:
            - AttributeName: "processingStage"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
        - IndexName: "ProcessingStageIndexV3"
          KeySchema:
            - AttributeName: "processingStage"
              KeyType: "HASH"
            - AttributeName: "startDate"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"